
from django.contrib import admin
from django.urls import path, include
from . import views
from .import ManagerViews, StaffViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('login', views.loginUser, name="login"),
    path('logout_user', views.logout_user, name="logout_user"),
    path('doLogin', views.doLogin, name="doLogin"),
    path('registration', views.registration, name="registration"),
    path('doRegistration', views.doRegistration, name="doRegistration"),
    
    #URLs for managers

    path('manager_home/', ManagerViews.manager_home_page, name="manager_home_page"),
    path('manager_profile/', ManagerViews.manager_profile, name="manager_profile"),
    path('manager_new_customer/', ManagerViews.manager_new_customer, name="manager_new_customer"),
    path('manager_new_customer_save/', ManagerViews.manager_new_customer_save, name="manager_new_customer_save"),
    path('manager_add_rejections/', ManagerViews.manager_add_rejections, name="manager_add_rejections"),
    path('manager_add_rejections_save/', ManagerViews.manager_add_rejections_save, name="manager_add_rejections_save"),
    path('manager_update_tools/', ManagerViews.manager_update_tools, name="manager_update_tools"),
    path('manager_view_tools/', ManagerViews.manager_view_tools, name="manager_view_tools"),
    path('manager_view_productions/', ManagerViews.manager_view_productions,
        name="manager_view_productions"),
    path('manager_view_parts/', ManagerViews.manager_view_parts, name="manager_view_parts"),
    path('manager_view_rejections/', ManagerViews.manager_view_rejections,
        name="manager_view_rejections"),
    path('manager_view_operations/', ManagerViews.manager_view_operations,
        name="manager_view_operations"),
    path('manager_add_parts/', ManagerViews.manager_add_parts, name = "manager_add_parts"),
    path('manager_get_production_on/', ManagerViews.manager_get_production_on,
        name="manager_get_production_on"),
    path('manager_update_production_today/', ManagerViews.manager_update_production_today,
        name="manager_update_production_today"),
     path('manager_view_orders/', ManagerViews.manager_view_orders,
        name="manager_view_orders"),
     path('manager_add_part_save/', ManagerViews.manager_add_part_save,
        name="manager_add_part_save"),
    path('manager_add_rejections_save/', ManagerViews.manager_add_rejections_save,
        name="manager_add_rejections_save"),
    path('manager_add_tools_save/', ManagerViews.manager_add_tools_save,
        name="manager_add_tools_save"),
    path('manager_update_tools_save/', ManagerViews.manager_update_tools_save,
        name="manager_update_tools_save"),
    path('manager_add_tools/', ManagerViews.manager_add_tools,
        name="manager_add_tools"),
    path('manager_update_production_today_save/', ManagerViews.manager_update_production_today_save,
        name="manager_update_production_today_save"),
    path('manager_change_price/', ManagerViews.manager_change_price,
        name="manager_change_price"),
    path('manager_change_price_save/', ManagerViews.manager_change_price_save,
        name="manager_change_price_save"),
    path('manager_update_lead/', ManagerViews.manager_update_lead,
        name="manager_update_lead"),
    path('manager_add_rejections/', ManagerViews.manager_add_rejections,
        name="manager_add_rejections"),
    path('change_rejection_status_save/<order>/<op_req>/', ManagerViews.change_rejection_status_save,
        name="change_rejection_status_save"),
    path('manager_update_lead_save/', ManagerViews.manager_update_lead_save,
        name="manager_update_lead_save"),
    path('manager_delete_parts_save/<par>/', ManagerViews.manager_delete_parts_save,
        name="manager_delete_parts_save"),
    path('manager_delete_rejections/<order_id>/<op_req>/', ManagerViews.manager_delete_rejections,
        name="manager_delete_rejections"),
    path('manager_add_operations', ManagerViews.manager_add_operations,
        name="manager_add_operations"),
    path('manager_add_operations_save', ManagerViews.manager_add_operations_save,
        name="manager_add_operations_save"),
path('change_status', ManagerViews.change_status,
        name="change_status"),

    #URLs for workers

    path('staff_home_page/', StaffViews.staff_home_page, name = "staff_home_page"),
    path('staff_profile/', StaffViews.staff_profile, name = "staff_profile"),
    path('staff_update_tools_save/', StaffViews.staff_update_tools_save, name = "staff_update_tools_save"),
    path('staff_update_processes_save/', StaffViews.staff_update_processes_save, name = "staff_update_processes_save"),
    path('staff_change_status/', StaffViews.staff_change_status, name = "staff_change_status"),
    path('staff_delete_rejections/', StaffViews.staff_delete_rejections, name = "staff_delete_rejections"),
    path('staff_change_rejection_status_save/', StaffViews.staff_change_rejection_status_save, name = "staff_change_rejection_status_save"),
    path('staff_view_customer/', StaffViews.staff_view_customer, name="staff_view_customer"),
    path('staff_update_tools/', StaffViews.staff_update_tools, name="staff_update_tools"),
    path('staff_view_rejections/', StaffViews.staff_view_rejections,
        name="staff_view_rejections"),
    path('staff_view_tools/', StaffViews.staff_view_tools,
        name="staff_view_tools"),
    path('staff_view_productions/', StaffViews.staff_view_productions,
        name="staff_view_productions"),
    path('staff_update_processes',
        StaffViews.staff_update_processes, 
        name="staff_update_processes")
]