# Generated by Django 3.2.12 on 2022-10-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('request_date', models.DateField()),
                ('contact', models.IntegerField()),
                ('alternate_contact', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('deadline', models.DateField()),
                ('part_name', models.CharField(max_length=40)),
                ('order_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_today', models.IntegerField()),
                ('date', models.DateField()),
                ('expected_production_rate', models.IntegerField()),
                ('current_production_rate', models.IntegerField()),
                ('lead', models.CharField(max_length=50, null=True)),
                ('lead_contact', models.IntegerField(null=True)),
                ('lead_email', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(choices=[('1', 'Procuring Raw Material'), ('2', 'Cleaning'), ('3', 'Heating'), ('4', 'Shaping'), ('5', 'Cooling'), ('6', 'Cutting'), ('7', 'Resting'), ('8', 'Polishing'), ('9', 'Packing')], default='6', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='part_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parts',
            fields=[
                ('part_name', models.CharField(max_length=40)),
                ('quantity_manufactured', models.IntegerField(null=True)),
                ('required_quantity', models.IntegerField()),
                ('operation_done', models.CharField(choices=[('1', 'Procuring Raw Material'), ('2', 'Cleaning'), ('3', 'Heating'), ('4', 'Shaping'), ('5', 'Cooling'), ('6', 'Cutting'), ('7', 'Resting'), ('8', 'Polishing'), ('9', 'Packing')], default='1', max_length=1)),
                ('batch_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mfd_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='rejections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_date', models.DateField()),
                ('rejection_amount', models.IntegerField()),
                ('operations_required', models.CharField(choices=[('1', 'Procuring Raw Material'), ('2', 'Cleaning'), ('3', 'Heating'), ('4', 'Shaping'), ('5', 'Cooling'), ('6', 'Cutting'), ('7', 'Resting'), ('8', 'Polishing'), ('9', 'Packing')], max_length=1)),
                ('operation_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=40)),
                ('tool_life', models.IntegerField()),
                ('bought_on', models.DateField()),
                ('parts_manufactured', models.IntegerField(null=True)),
                ('num_polished', models.IntegerField(null=True)),
                ('last_polished_on', models.DateField(null=True)),
                ('max_polish', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='tools',
            constraint=models.UniqueConstraint(fields=('bought_on', 'tool_name'), name='prim_key_for_tools'),
        ),
        migrations.AddField(
            model_name='rejections',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_batch_id', to='inventory.parts'),
        ),
        migrations.AddField(
            model_name='rejections',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='rejections',
            name='part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.parts'),
        ),
        migrations.AddField(
            model_name='parts',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='part_cost',
            name='part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts'),
        ),
        migrations.AddField(
            model_name='operations',
            name='tools_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.tools'),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
    ]
